// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "3530d196d7f74c6c86c0779cba2bf07edf17788f7e1c4302a8f29487128d3375")
