// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "968b289c98809fa81505994a76b60e08cdfcb2b51cbc747c9817c82070560e23")
