// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "16bd59eff3697417ac153dd7f5ef4db715846071c00feb5e42b052a2225d2fb5")
